/*!\page LICENSE LICENSE

Copyright (C) 2003 by the Board of Trustees of Massachusetts Institute of
Technology, hereafter designated as the Copyright Owners.

License to use, copy, modify, sell and/or distribute this software and
its documentation for any purpose is hereby granted without royalty,
subject to the following terms and conditions:

1.  The above copyright notice and this permission notice must
appear in all copies of the software and related documentation.

2.  The names of the Copyright Owners may not be used in advertising or
publicity pertaining to distribution of the software without the specific,
prior written permission of the Copyright Owners.

3.  THE SOFTWARE IS PROVIDED "AS-IS" AND THE COPYRIGHT OWNERS MAKE NO
REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED, BY WAY OF EXAMPLE, BUT NOT
LIMITATION.  THE COPYRIGHT OWNERS MAKE NO REPRESENTATIONS OR WARRANTIES OF
MERCHANTABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE OR THAT THE USE OF THE
SOFTWARE WILL NOT INFRINGE ANY PATENTS, COPYRIGHTS TRADEMARKS OR OTHER
RIGHTS. THE COPYRIGHT OWNERS SHALL NOT BE LIABLE FOR ANY LIABILITY OR DAMAGES
WITH RESPECT TO ANY CLAIM BY LICENSEE OR ANY THIRD PARTY ON ACCOUNT OF, OR
ARISING FROM THE LICENSE, OR ANY SUBLICENSE OR USE OF THE SOFTWARE OR ANY
SERVICE OR SUPPORT.

LICENSEE shall indemnify, hold harmless and defend the Copyright Owners and
their trustees, officers, employees, students and agents against any and all
claims arising out of the exercise of any rights under this Agreement,
including, without limiting the generality of the foregoing, against any
damages, losses or liabilities whatsoever with respect to death or injury to
person or damage to property arising from or out of the possession, use, or
operation of Software or Licensed Program(s) by LICENSEE or its customers.

*/



#include "output.h"

#ifdef SU0914
char* current_output_fname = NULL;
FILE* current_output_file = NULL;

void dump_current_output(char* outp) {
	if (current_output_file != NULL) {
		fprintf(current_output_file, outp);
	} else {
		start_write_currents();
		if (current_output_file != NULL) {
			fprintf(current_output_file, outp);
			end_write_currents();
		}
	}
}

void start_write_currents(void) {
	if (current_output_fname != NULL) {
		current_output_file = fopen(current_output_fname, "a");
		if (current_output_file == NULL) {
			fprintf(stderr,
					"Warning: cannot open output file '%s' for append access\n.",
					current_output_fname);
		}
	}
}

void end_write_currents(void) {
	if (current_output_file != NULL) {
		fclose(current_output_file);
		current_output_file = NULL;
	}
}

void place_current_output(EXTERNAL* in_port, EXTERNAL* out_port, CX current) {
	if (current_output_file != NULL) {
		fprintf(current_output_file, "%s %s %.10g%s%.10gj\n", in_port->portname,
				out_port->portname, current.real,
				(current.imag >= 0 ? " +" : " "), current.imag);
		//start bap
		//fprintf(current_output_file, "  %.10g%s%.10g;\n", current.real,
			//(current.imag >= 0 ? " ," : ","), current.imag);
		//end bap
	}
}

void declare_current_output_file(char* outfile) {
	current_output_fname = outfile;
	if (current_output_fname != NULL) {
		current_output_file = fopen(current_output_fname, "w");
		if (current_output_file == NULL) {
			fprintf(stderr,
					"Warning: cannot open output file '%s' for write access.\n",
					current_output_fname);
		} else {
			fprintf(current_output_file,
					"* Port current output file generated by FastHenry %s\n",
					FHVERSION);
		}
		fclose(current_output_file);
		current_output_file = NULL;
	}
}
#endif
